<?php
// auto-generated by sfRoutingConfigHandler
// date: 2013/05/08 12:00:54
return array(
'homepage' => new sfRoute('/', array (
  'module' => 'homeGuest',
  'action' => 'index',
), array (
), array (
)),
'default_index' => new sfRoute('/:module', array (
  'action' => 'index',
), array (
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
'homeGuest' => new sfRoute('/homeGuest/index', array (
  'module' => 'homeGuest',
  'action' => 'index',
), array (
), array (
)),
'action_to_template' => new sfRoute('/homeGuest/actiontotem', array (
  'module' => 'homeGuest',
  'action' => 'actiontotem',
), array (
), array (
)),
);
