propel:
  student:
    _attributes: { phpName: Student }
    id:
    name:        varchar(255)
    grade:       integer
    teacher_id:  
    created_at:
  teacher:
    _attributes: { phpName: Teacher }
    id:
    name:        varchar(255)
    type:        varchar(255)
    created_at:
