<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/05/14 16:15:56
sfConfig::add(array(
  'app_version' => '1.0',
  'app_mail_web_master' => '10000@qq.com',
  'app_mail_contact' => '20000@qq.com',
));
