<?php
// auto-generated by sfViewConfigHandler
// date: 2013/05/22 15:42:50
$response = $this->context->getResponse();

if ($this->actionName.$this->viewName == 'homeSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}

if ($templateName.$this->viewName == 'homeSuccess')
{
  if (!is_null($layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout')))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else
  {
    $this->setDecoratorTemplate('' == '' ? false : ''.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addHttpMeta('charset', 'UTF-8', false);
  $response->addMeta('title', 'Roy Studio', false, false);
  $response->addMeta('description', 'Login and Registration Form with HTML5 and CSS3', false, false);
  $response->addMeta('keywords', 'html5, css3, form, switch, animation, :target, pseudo-class', false, false);
  $response->addMeta('language', 'en', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('viewport', 'width=device-width, initial-scale=1.0', false, false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('animate-custom.css', '', array ());
  $response->addStylesheet('demo.css', '', array ());
  $response->addStylesheet('style.css', '', array ());
}
else
{
  if (!is_null($layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout')))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (is_null($this->getDecoratorTemplate()) && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Roy Studio', false, false);

  $response->addStylesheet('main.css', '', array ());
}

