<?php
// auto-generated by sfCacheConfigHandler
// date: 2013/05/22 15:42:50
$this->addCache($moduleName, 'index', array('withLayout' => false, 'lifeTime' => 5, 'clientLifeTime' => 5, 'contextual' => false, 'vary' => array ()));
$this->addCache($moduleName, '_currentDate', array('withLayout' => false, 'lifeTime' => 86400, 'clientLifeTime' => 86400, 'contextual' => false, 'vary' => array ()));
$this->addCache($moduleName, 'All', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

